from mflux.models.common.lora.mapping.lora_mapping import LoRAMapping, LoRATarget


class ErnieLoRAMapping(LoRAMapping):
    @staticmethod
    def get_mapping() -> list[LoRATarget]:
        return [
            LoRATarget(
                model_path="adaln_modulation",
                possible_up_patterns=[
                    "transformer.adaln_modulation.lora_B.weight",
                    "diffusion_model.adaln_modulation.lora_B.weight",
                    "lora_unet_adaLN_modulation_1.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.adaln_modulation.lora_A.weight",
                    "diffusion_model.adaln_modulation.lora_A.weight",
                    "lora_unet_adaLN_modulation_1.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.adaln_modulation.alpha",
                    "diffusion_model.adaln_modulation.alpha",
                    "lora_unet_adaLN_modulation_1.alpha",
                ],
            ),
            LoRATarget(
                model_path="time_embedding.linear_1",
                possible_up_patterns=[
                    "transformer.time_embedding.linear_1.lora_B.weight",
                    "diffusion_model.time_embedding.linear_1.lora_B.weight",
                    "lora_unet_time_embedding_linear_1.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.time_embedding.linear_1.lora_A.weight",
                    "diffusion_model.time_embedding.linear_1.lora_A.weight",
                    "lora_unet_time_embedding_linear_1.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.time_embedding.linear_1.alpha",
                    "diffusion_model.time_embedding.linear_1.alpha",
                    "lora_unet_time_embedding_linear_1.alpha",
                ],
            ),
            LoRATarget(
                model_path="time_embedding.linear_2",
                possible_up_patterns=[
                    "transformer.time_embedding.linear_2.lora_B.weight",
                    "diffusion_model.time_embedding.linear_2.lora_B.weight",
                    "lora_unet_time_embedding_linear_2.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.time_embedding.linear_2.lora_A.weight",
                    "diffusion_model.time_embedding.linear_2.lora_A.weight",
                    "lora_unet_time_embedding_linear_2.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.time_embedding.linear_2.alpha",
                    "diffusion_model.time_embedding.linear_2.alpha",
                    "lora_unet_time_embedding_linear_2.alpha",
                ],
            ),
            LoRATarget(
                model_path="final_norm.linear",
                possible_up_patterns=[
                    "transformer.final_norm.linear.lora_B.weight",
                    "diffusion_model.final_norm.linear.lora_B.weight",
                    "lora_unet_final_norm_linear.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.final_norm.linear.lora_A.weight",
                    "diffusion_model.final_norm.linear.lora_A.weight",
                    "lora_unet_final_norm_linear.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.final_norm.linear.alpha",
                    "diffusion_model.final_norm.linear.alpha",
                    "lora_unet_final_norm_linear.alpha",
                ],
            ),
            LoRATarget(
                model_path="text_proj",
                possible_up_patterns=[
                    "transformer.text_proj.lora_B.weight",
                    "diffusion_model.text_proj.lora_B.weight",
                    "lora_unet_text_proj.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.text_proj.lora_A.weight",
                    "diffusion_model.text_proj.lora_A.weight",
                    "lora_unet_text_proj.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.text_proj.alpha",
                    "diffusion_model.text_proj.alpha",
                    "lora_unet_text_proj.alpha",
                ],
            ),
            LoRATarget(
                model_path="final_linear",
                possible_up_patterns=[
                    "transformer.final_linear.lora_B.weight",
                    "diffusion_model.final_linear.lora_B.weight",
                    "lora_unet_final_linear.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.final_linear.lora_A.weight",
                    "diffusion_model.final_linear.lora_A.weight",
                    "lora_unet_final_linear.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.final_linear.alpha",
                    "diffusion_model.final_linear.alpha",
                    "lora_unet_final_linear.alpha",
                ],
            ),
            LoRATarget(
                model_path="layers.{block}.self_attention.to_q",
                possible_up_patterns=[
                    "transformer.layers.{block}.self_attention.to_q.lora_B.weight",
                    "diffusion_model.layers.{block}.self_attention.to_q.lora_B.weight",
                    "layers.{block}.self_attention.to_q.lora_B.weight",
                    "lora_unet_layers_{block}_self_attention_to_q.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.layers.{block}.self_attention.to_q.lora_A.weight",
                    "diffusion_model.layers.{block}.self_attention.to_q.lora_A.weight",
                    "layers.{block}.self_attention.to_q.lora_A.weight",
                    "lora_unet_layers_{block}_self_attention_to_q.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.layers.{block}.self_attention.to_q.alpha",
                    "diffusion_model.layers.{block}.self_attention.to_q.alpha",
                    "layers.{block}.self_attention.to_q.alpha",
                    "lora_unet_layers_{block}_self_attention_to_q.alpha",
                ],
            ),
            LoRATarget(
                model_path="layers.{block}.self_attention.to_k",
                possible_up_patterns=[
                    "transformer.layers.{block}.self_attention.to_k.lora_B.weight",
                    "diffusion_model.layers.{block}.self_attention.to_k.lora_B.weight",
                    "layers.{block}.self_attention.to_k.lora_B.weight",
                    "lora_unet_layers_{block}_self_attention_to_k.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.layers.{block}.self_attention.to_k.lora_A.weight",
                    "diffusion_model.layers.{block}.self_attention.to_k.lora_A.weight",
                    "layers.{block}.self_attention.to_k.lora_A.weight",
                    "lora_unet_layers_{block}_self_attention_to_k.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.layers.{block}.self_attention.to_k.alpha",
                    "diffusion_model.layers.{block}.self_attention.to_k.alpha",
                    "layers.{block}.self_attention.to_k.alpha",
                    "lora_unet_layers_{block}_self_attention_to_k.alpha",
                ],
            ),
            LoRATarget(
                model_path="layers.{block}.self_attention.to_v",
                possible_up_patterns=[
                    "transformer.layers.{block}.self_attention.to_v.lora_B.weight",
                    "diffusion_model.layers.{block}.self_attention.to_v.lora_B.weight",
                    "layers.{block}.self_attention.to_v.lora_B.weight",
                    "lora_unet_layers_{block}_self_attention_to_v.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.layers.{block}.self_attention.to_v.lora_A.weight",
                    "diffusion_model.layers.{block}.self_attention.to_v.lora_A.weight",
                    "layers.{block}.self_attention.to_v.lora_A.weight",
                    "lora_unet_layers_{block}_self_attention_to_v.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.layers.{block}.self_attention.to_v.alpha",
                    "diffusion_model.layers.{block}.self_attention.to_v.alpha",
                    "layers.{block}.self_attention.to_v.alpha",
                    "lora_unet_layers_{block}_self_attention_to_v.alpha",
                ],
            ),
            LoRATarget(
                model_path="layers.{block}.self_attention.to_out.0",
                possible_up_patterns=[
                    "transformer.layers.{block}.self_attention.to_out.0.lora_B.weight",
                    "diffusion_model.layers.{block}.self_attention.to_out.0.lora_B.weight",
                    "layers.{block}.self_attention.to_out.0.lora_B.weight",
                    "lora_unet_layers_{block}_self_attention_to_out_0.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.layers.{block}.self_attention.to_out.0.lora_A.weight",
                    "diffusion_model.layers.{block}.self_attention.to_out.0.lora_A.weight",
                    "layers.{block}.self_attention.to_out.0.lora_A.weight",
                    "lora_unet_layers_{block}_self_attention_to_out_0.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.layers.{block}.self_attention.to_out.0.alpha",
                    "diffusion_model.layers.{block}.self_attention.to_out.0.alpha",
                    "layers.{block}.self_attention.to_out.0.alpha",
                    "lora_unet_layers_{block}_self_attention_to_out_0.alpha",
                ],
            ),
            LoRATarget(
                model_path="layers.{block}.mlp.gate_proj",
                possible_up_patterns=[
                    "transformer.layers.{block}.mlp.gate_proj.lora_B.weight",
                    "diffusion_model.layers.{block}.mlp.gate_proj.lora_B.weight",
                    "layers.{block}.mlp.gate_proj.lora_B.weight",
                    "lora_unet_layers_{block}_mlp_gate_proj.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.layers.{block}.mlp.gate_proj.lora_A.weight",
                    "diffusion_model.layers.{block}.mlp.gate_proj.lora_A.weight",
                    "layers.{block}.mlp.gate_proj.lora_A.weight",
                    "lora_unet_layers_{block}_mlp_gate_proj.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.layers.{block}.mlp.gate_proj.alpha",
                    "diffusion_model.layers.{block}.mlp.gate_proj.alpha",
                    "layers.{block}.mlp.gate_proj.alpha",
                    "lora_unet_layers_{block}_mlp_gate_proj.alpha",
                ],
            ),
            LoRATarget(
                model_path="layers.{block}.mlp.up_proj",
                possible_up_patterns=[
                    "transformer.layers.{block}.mlp.up_proj.lora_B.weight",
                    "diffusion_model.layers.{block}.mlp.up_proj.lora_B.weight",
                    "layers.{block}.mlp.up_proj.lora_B.weight",
                    "lora_unet_layers_{block}_mlp_up_proj.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.layers.{block}.mlp.up_proj.lora_A.weight",
                    "diffusion_model.layers.{block}.mlp.up_proj.lora_A.weight",
                    "layers.{block}.mlp.up_proj.lora_A.weight",
                    "lora_unet_layers_{block}_mlp_up_proj.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.layers.{block}.mlp.up_proj.alpha",
                    "diffusion_model.layers.{block}.mlp.up_proj.alpha",
                    "layers.{block}.mlp.up_proj.alpha",
                    "lora_unet_layers_{block}_mlp_up_proj.alpha",
                ],
            ),
            LoRATarget(
                model_path="layers.{block}.mlp.linear_fc2",
                possible_up_patterns=[
                    "transformer.layers.{block}.mlp.linear_fc2.lora_B.weight",
                    "diffusion_model.layers.{block}.mlp.linear_fc2.lora_B.weight",
                    "layers.{block}.mlp.linear_fc2.lora_B.weight",
                    "lora_unet_layers_{block}_mlp_linear_fc2.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer.layers.{block}.mlp.linear_fc2.lora_A.weight",
                    "diffusion_model.layers.{block}.mlp.linear_fc2.lora_A.weight",
                    "layers.{block}.mlp.linear_fc2.lora_A.weight",
                    "lora_unet_layers_{block}_mlp_linear_fc2.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer.layers.{block}.mlp.linear_fc2.alpha",
                    "diffusion_model.layers.{block}.mlp.linear_fc2.alpha",
                    "layers.{block}.mlp.linear_fc2.alpha",
                    "lora_unet_layers_{block}_mlp_linear_fc2.alpha",
                ],
            ),
        ]
