from typing import List

import mlx.core as mx

from mflux.models.common.weights.mapping.weight_mapping import WeightMapping, WeightTarget


def transpose_conv2d_weight(weight: mx.array) -> mx.array:
    return weight.transpose(0, 2, 3, 1)


class ZImageWeightMapping(WeightMapping):
    @staticmethod
    def get_text_encoder_mapping() -> List[WeightTarget]:
        return [
            WeightTarget(
                mlx_path="embed_tokens.weight",
                hf_patterns=["model.embed_tokens.weight"],
            ),
            WeightTarget(
                mlx_path="norm.weight",
                hf_patterns=["model.norm.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.input_layernorm.weight",
                hf_patterns=["model.layers.{layer}.input_layernorm.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.post_attention_layernorm.weight",
                hf_patterns=["model.layers.{layer}.post_attention_layernorm.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.self_attn.q_proj.weight",
                hf_patterns=["model.layers.{layer}.self_attn.q_proj.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.self_attn.k_proj.weight",
                hf_patterns=["model.layers.{layer}.self_attn.k_proj.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.self_attn.v_proj.weight",
                hf_patterns=["model.layers.{layer}.self_attn.v_proj.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.self_attn.o_proj.weight",
                hf_patterns=["model.layers.{layer}.self_attn.o_proj.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.self_attn.q_norm.weight",
                hf_patterns=["model.layers.{layer}.self_attn.q_norm.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.self_attn.k_norm.weight",
                hf_patterns=["model.layers.{layer}.self_attn.k_norm.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.mlp.gate_proj.weight",
                hf_patterns=["model.layers.{layer}.mlp.gate_proj.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.mlp.up_proj.weight",
                hf_patterns=["model.layers.{layer}.mlp.up_proj.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.mlp.down_proj.weight",
                hf_patterns=["model.layers.{layer}.mlp.down_proj.weight"],
            ),
        ]

    @staticmethod
    def get_vae_mapping() -> List[WeightTarget]:
        return [
            WeightTarget(
                mlx_path="encoder.conv_in.conv2d.weight",
                hf_patterns=["encoder.conv_in.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="encoder.conv_in.conv2d.bias",
                hf_patterns=["encoder.conv_in.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.resnets.{res}.norm1.weight",
                hf_patterns=["encoder.down_blocks.{block}.resnets.{res}.norm1.weight"],
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.resnets.{res}.norm1.bias",
                hf_patterns=["encoder.down_blocks.{block}.resnets.{res}.norm1.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.resnets.{res}.conv1.weight",
                hf_patterns=["encoder.down_blocks.{block}.resnets.{res}.conv1.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.resnets.{res}.conv1.bias",
                hf_patterns=["encoder.down_blocks.{block}.resnets.{res}.conv1.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.resnets.{res}.norm2.weight",
                hf_patterns=["encoder.down_blocks.{block}.resnets.{res}.norm2.weight"],
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.resnets.{res}.norm2.bias",
                hf_patterns=["encoder.down_blocks.{block}.resnets.{res}.norm2.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.resnets.{res}.conv2.weight",
                hf_patterns=["encoder.down_blocks.{block}.resnets.{res}.conv2.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.resnets.{res}.conv2.bias",
                hf_patterns=["encoder.down_blocks.{block}.resnets.{res}.conv2.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.resnets.{res}.conv_shortcut.weight",
                hf_patterns=["encoder.down_blocks.{block}.resnets.{res}.conv_shortcut.weight"],
                transform=transpose_conv2d_weight,
                required=False,
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.resnets.{res}.conv_shortcut.bias",
                hf_patterns=["encoder.down_blocks.{block}.resnets.{res}.conv_shortcut.bias"],
                required=False,
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.downsamplers.0.conv.weight",
                hf_patterns=["encoder.down_blocks.{block}.downsamplers.0.conv.weight"],
                transform=transpose_conv2d_weight,
                required=False,
            ),
            WeightTarget(
                mlx_path="encoder.down_blocks.{block}.downsamplers.0.conv.bias",
                hf_patterns=["encoder.down_blocks.{block}.downsamplers.0.conv.bias"],
                required=False,
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.resnets.{i}.norm1.weight",
                hf_patterns=["encoder.mid_block.resnets.{i}.norm1.weight"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.resnets.{i}.norm1.bias",
                hf_patterns=["encoder.mid_block.resnets.{i}.norm1.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.resnets.{i}.conv1.weight",
                hf_patterns=["encoder.mid_block.resnets.{i}.conv1.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.resnets.{i}.conv1.bias",
                hf_patterns=["encoder.mid_block.resnets.{i}.conv1.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.resnets.{i}.norm2.weight",
                hf_patterns=["encoder.mid_block.resnets.{i}.norm2.weight"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.resnets.{i}.norm2.bias",
                hf_patterns=["encoder.mid_block.resnets.{i}.norm2.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.resnets.{i}.conv2.weight",
                hf_patterns=["encoder.mid_block.resnets.{i}.conv2.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.resnets.{i}.conv2.bias",
                hf_patterns=["encoder.mid_block.resnets.{i}.conv2.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.attentions.0.group_norm.weight",
                hf_patterns=["encoder.mid_block.attentions.0.group_norm.weight"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.attentions.0.group_norm.bias",
                hf_patterns=["encoder.mid_block.attentions.0.group_norm.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.attentions.0.to_q.weight",
                hf_patterns=["encoder.mid_block.attentions.0.to_q.weight"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.attentions.0.to_q.bias",
                hf_patterns=["encoder.mid_block.attentions.0.to_q.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.attentions.0.to_k.weight",
                hf_patterns=["encoder.mid_block.attentions.0.to_k.weight"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.attentions.0.to_k.bias",
                hf_patterns=["encoder.mid_block.attentions.0.to_k.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.attentions.0.to_v.weight",
                hf_patterns=["encoder.mid_block.attentions.0.to_v.weight"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.attentions.0.to_v.bias",
                hf_patterns=["encoder.mid_block.attentions.0.to_v.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.attentions.0.to_out.0.weight",
                hf_patterns=["encoder.mid_block.attentions.0.to_out.0.weight"],
            ),
            WeightTarget(
                mlx_path="encoder.mid_block.attentions.0.to_out.0.bias",
                hf_patterns=["encoder.mid_block.attentions.0.to_out.0.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.conv_norm_out.norm.weight",
                hf_patterns=["encoder.conv_norm_out.weight"],
            ),
            WeightTarget(
                mlx_path="encoder.conv_norm_out.norm.bias",
                hf_patterns=["encoder.conv_norm_out.bias"],
            ),
            WeightTarget(
                mlx_path="encoder.conv_out.conv2d.weight",
                hf_patterns=["encoder.conv_out.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="encoder.conv_out.conv2d.bias",
                hf_patterns=["encoder.conv_out.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.conv_in.conv.weight",
                hf_patterns=["decoder.conv_in.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="decoder.conv_in.conv.bias",
                hf_patterns=["decoder.conv_in.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.resnets.{i}.norm1.weight",
                hf_patterns=["decoder.mid_block.resnets.{i}.norm1.weight"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.resnets.{i}.norm1.bias",
                hf_patterns=["decoder.mid_block.resnets.{i}.norm1.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.resnets.{i}.conv1.weight",
                hf_patterns=["decoder.mid_block.resnets.{i}.conv1.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.resnets.{i}.conv1.bias",
                hf_patterns=["decoder.mid_block.resnets.{i}.conv1.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.resnets.{i}.norm2.weight",
                hf_patterns=["decoder.mid_block.resnets.{i}.norm2.weight"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.resnets.{i}.norm2.bias",
                hf_patterns=["decoder.mid_block.resnets.{i}.norm2.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.resnets.{i}.conv2.weight",
                hf_patterns=["decoder.mid_block.resnets.{i}.conv2.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.resnets.{i}.conv2.bias",
                hf_patterns=["decoder.mid_block.resnets.{i}.conv2.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.attentions.0.group_norm.weight",
                hf_patterns=["decoder.mid_block.attentions.0.group_norm.weight"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.attentions.0.group_norm.bias",
                hf_patterns=["decoder.mid_block.attentions.0.group_norm.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.attentions.0.to_q.weight",
                hf_patterns=["decoder.mid_block.attentions.0.to_q.weight"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.attentions.0.to_q.bias",
                hf_patterns=["decoder.mid_block.attentions.0.to_q.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.attentions.0.to_k.weight",
                hf_patterns=["decoder.mid_block.attentions.0.to_k.weight"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.attentions.0.to_k.bias",
                hf_patterns=["decoder.mid_block.attentions.0.to_k.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.attentions.0.to_v.weight",
                hf_patterns=["decoder.mid_block.attentions.0.to_v.weight"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.attentions.0.to_v.bias",
                hf_patterns=["decoder.mid_block.attentions.0.to_v.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.attentions.0.to_out.0.weight",
                hf_patterns=["decoder.mid_block.attentions.0.to_out.0.weight"],
            ),
            WeightTarget(
                mlx_path="decoder.mid_block.attentions.0.to_out.0.bias",
                hf_patterns=["decoder.mid_block.attentions.0.to_out.0.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.resnets.{res}.norm1.weight",
                hf_patterns=["decoder.up_blocks.{block}.resnets.{res}.norm1.weight"],
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.resnets.{res}.norm1.bias",
                hf_patterns=["decoder.up_blocks.{block}.resnets.{res}.norm1.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.resnets.{res}.conv1.weight",
                hf_patterns=["decoder.up_blocks.{block}.resnets.{res}.conv1.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.resnets.{res}.conv1.bias",
                hf_patterns=["decoder.up_blocks.{block}.resnets.{res}.conv1.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.resnets.{res}.norm2.weight",
                hf_patterns=["decoder.up_blocks.{block}.resnets.{res}.norm2.weight"],
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.resnets.{res}.norm2.bias",
                hf_patterns=["decoder.up_blocks.{block}.resnets.{res}.norm2.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.resnets.{res}.conv2.weight",
                hf_patterns=["decoder.up_blocks.{block}.resnets.{res}.conv2.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.resnets.{res}.conv2.bias",
                hf_patterns=["decoder.up_blocks.{block}.resnets.{res}.conv2.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.resnets.{res}.conv_shortcut.weight",
                hf_patterns=["decoder.up_blocks.{block}.resnets.{res}.conv_shortcut.weight"],
                transform=transpose_conv2d_weight,
                required=False,
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.resnets.{res}.conv_shortcut.bias",
                hf_patterns=["decoder.up_blocks.{block}.resnets.{res}.conv_shortcut.bias"],
                required=False,
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.upsamplers.0.conv.weight",
                hf_patterns=["decoder.up_blocks.{block}.upsamplers.0.conv.weight"],
                transform=transpose_conv2d_weight,
                required=False,
            ),
            WeightTarget(
                mlx_path="decoder.up_blocks.{block}.upsamplers.0.conv.bias",
                hf_patterns=["decoder.up_blocks.{block}.upsamplers.0.conv.bias"],
                required=False,
            ),
            WeightTarget(
                mlx_path="decoder.conv_norm_out.norm.weight",
                hf_patterns=["decoder.conv_norm_out.weight"],
            ),
            WeightTarget(
                mlx_path="decoder.conv_norm_out.norm.bias",
                hf_patterns=["decoder.conv_norm_out.bias"],
            ),
            WeightTarget(
                mlx_path="decoder.conv_out.conv.weight",
                hf_patterns=["decoder.conv_out.weight"],
                transform=transpose_conv2d_weight,
            ),
            WeightTarget(
                mlx_path="decoder.conv_out.conv.bias",
                hf_patterns=["decoder.conv_out.bias"],
            ),
        ]

    @staticmethod
    def get_transformer_mapping() -> List[WeightTarget]:
        return [
            WeightTarget(
                mlx_path="t_embedder.linear1.weight",
                hf_patterns=["t_embedder.mlp.0.weight"],
            ),
            WeightTarget(
                mlx_path="t_embedder.linear1.bias",
                hf_patterns=["t_embedder.mlp.0.bias"],
            ),
            WeightTarget(
                mlx_path="t_embedder.linear2.weight",
                hf_patterns=["t_embedder.mlp.2.weight"],
            ),
            WeightTarget(
                mlx_path="t_embedder.linear2.bias",
                hf_patterns=["t_embedder.mlp.2.bias"],
            ),
            WeightTarget(
                mlx_path="cap_embedder.0.weight",
                hf_patterns=["cap_embedder.0.weight"],
            ),
            WeightTarget(
                mlx_path="cap_embedder.1.weight",
                hf_patterns=["cap_embedder.1.weight"],
            ),
            WeightTarget(
                mlx_path="cap_embedder.1.bias",
                hf_patterns=["cap_embedder.1.bias"],
            ),
            WeightTarget(
                mlx_path="x_pad_token",
                hf_patterns=["x_pad_token"],
            ),
            WeightTarget(
                mlx_path="cap_pad_token",
                hf_patterns=["cap_pad_token"],
            ),
            WeightTarget(
                mlx_path="all_x_embedder.2-1.weight",
                hf_patterns=["all_x_embedder.2-1.weight"],
            ),
            WeightTarget(
                mlx_path="all_x_embedder.2-1.bias",
                hf_patterns=["all_x_embedder.2-1.bias"],
            ),
            WeightTarget(
                mlx_path="all_final_layer.2-1.linear.weight",
                hf_patterns=["all_final_layer.2-1.linear.weight"],
            ),
            WeightTarget(
                mlx_path="all_final_layer.2-1.linear.bias",
                hf_patterns=["all_final_layer.2-1.linear.bias"],
            ),
            WeightTarget(
                mlx_path="all_final_layer.2-1.adaLN_modulation.0.weight",
                hf_patterns=["all_final_layer.2-1.adaLN_modulation.1.weight"],
            ),
            WeightTarget(
                mlx_path="all_final_layer.2-1.adaLN_modulation.0.bias",
                hf_patterns=["all_final_layer.2-1.adaLN_modulation.1.bias"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.adaLN_modulation.0.weight",
                hf_patterns=["noise_refiner.{layer}.adaLN_modulation.0.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.adaLN_modulation.0.bias",
                hf_patterns=["noise_refiner.{layer}.adaLN_modulation.0.bias"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.attention.to_q.weight",
                hf_patterns=["noise_refiner.{layer}.attention.to_q.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.attention.to_k.weight",
                hf_patterns=["noise_refiner.{layer}.attention.to_k.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.attention.to_v.weight",
                hf_patterns=["noise_refiner.{layer}.attention.to_v.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.attention.to_out.0.weight",
                hf_patterns=["noise_refiner.{layer}.attention.to_out.0.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.attention.norm_q.weight",
                hf_patterns=["noise_refiner.{layer}.attention.norm_q.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.attention.norm_k.weight",
                hf_patterns=["noise_refiner.{layer}.attention.norm_k.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.attention_norm1.weight",
                hf_patterns=["noise_refiner.{layer}.attention_norm1.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.attention_norm2.weight",
                hf_patterns=["noise_refiner.{layer}.attention_norm2.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.ffn_norm1.weight",
                hf_patterns=["noise_refiner.{layer}.ffn_norm1.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.ffn_norm2.weight",
                hf_patterns=["noise_refiner.{layer}.ffn_norm2.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.feed_forward.w1.weight",
                hf_patterns=["noise_refiner.{layer}.feed_forward.w1.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.feed_forward.w2.weight",
                hf_patterns=["noise_refiner.{layer}.feed_forward.w2.weight"],
            ),
            WeightTarget(
                mlx_path="noise_refiner.{layer}.feed_forward.w3.weight",
                hf_patterns=["noise_refiner.{layer}.feed_forward.w3.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.attention.to_q.weight",
                hf_patterns=["context_refiner.{layer}.attention.to_q.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.attention.to_k.weight",
                hf_patterns=["context_refiner.{layer}.attention.to_k.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.attention.to_v.weight",
                hf_patterns=["context_refiner.{layer}.attention.to_v.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.attention.to_out.0.weight",
                hf_patterns=["context_refiner.{layer}.attention.to_out.0.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.attention.norm_q.weight",
                hf_patterns=["context_refiner.{layer}.attention.norm_q.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.attention.norm_k.weight",
                hf_patterns=["context_refiner.{layer}.attention.norm_k.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.attention_norm1.weight",
                hf_patterns=["context_refiner.{layer}.attention_norm1.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.attention_norm2.weight",
                hf_patterns=["context_refiner.{layer}.attention_norm2.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.ffn_norm1.weight",
                hf_patterns=["context_refiner.{layer}.ffn_norm1.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.ffn_norm2.weight",
                hf_patterns=["context_refiner.{layer}.ffn_norm2.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.feed_forward.w1.weight",
                hf_patterns=["context_refiner.{layer}.feed_forward.w1.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.feed_forward.w2.weight",
                hf_patterns=["context_refiner.{layer}.feed_forward.w2.weight"],
            ),
            WeightTarget(
                mlx_path="context_refiner.{layer}.feed_forward.w3.weight",
                hf_patterns=["context_refiner.{layer}.feed_forward.w3.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.adaLN_modulation.0.weight",
                hf_patterns=["layers.{layer}.adaLN_modulation.0.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.adaLN_modulation.0.bias",
                hf_patterns=["layers.{layer}.adaLN_modulation.0.bias"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.attention.to_q.weight",
                hf_patterns=["layers.{layer}.attention.to_q.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.attention.to_k.weight",
                hf_patterns=["layers.{layer}.attention.to_k.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.attention.to_v.weight",
                hf_patterns=["layers.{layer}.attention.to_v.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.attention.to_out.0.weight",
                hf_patterns=["layers.{layer}.attention.to_out.0.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.attention.norm_q.weight",
                hf_patterns=["layers.{layer}.attention.norm_q.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.attention.norm_k.weight",
                hf_patterns=["layers.{layer}.attention.norm_k.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.attention_norm1.weight",
                hf_patterns=["layers.{layer}.attention_norm1.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.attention_norm2.weight",
                hf_patterns=["layers.{layer}.attention_norm2.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.ffn_norm1.weight",
                hf_patterns=["layers.{layer}.ffn_norm1.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.ffn_norm2.weight",
                hf_patterns=["layers.{layer}.ffn_norm2.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.feed_forward.w1.weight",
                hf_patterns=["layers.{layer}.feed_forward.w1.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.feed_forward.w2.weight",
                hf_patterns=["layers.{layer}.feed_forward.w2.weight"],
            ),
            WeightTarget(
                mlx_path="layers.{layer}.feed_forward.w3.weight",
                hf_patterns=["layers.{layer}.feed_forward.w3.weight"],
            ),
        ]
