from mflux.models.common.weights.mapping.weight_mapping import WeightTarget


class ZImageControlnetWeightMapping:
    @staticmethod
    def get_controlnet_mapping() -> list[WeightTarget]:
        # Note: Union checkpoints are expected to provide keys like:
        # - control_all_x_embedder.2-1.*
        # - control_layers.{i}.*
        # - (2.1) control_noise_refiner.{i}.*
        return [
            WeightTarget(
                to_pattern="control_all_x_embedder.2-1.weight",
                from_pattern=["control_all_x_embedder.2-1.weight"],
            ),
            WeightTarget(
                to_pattern="control_all_x_embedder.2-1.bias",
                from_pattern=["control_all_x_embedder.2-1.bias"],
            ),
            # Main control layers (Union: 15 blocks)
            WeightTarget(
                to_pattern="control_layers.{block}.adaLN_modulation.0.weight",
                from_pattern=["control_layers.{block}.adaLN_modulation.0.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.adaLN_modulation.0.bias",
                from_pattern=["control_layers.{block}.adaLN_modulation.0.bias"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.attention.to_q.weight",
                from_pattern=["control_layers.{block}.attention.to_q.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.attention.to_k.weight",
                from_pattern=["control_layers.{block}.attention.to_k.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.attention.to_v.weight",
                from_pattern=["control_layers.{block}.attention.to_v.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.attention.to_out.0.weight",
                from_pattern=["control_layers.{block}.attention.to_out.0.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.attention.norm_q.weight",
                from_pattern=["control_layers.{block}.attention.norm_q.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.attention.norm_k.weight",
                from_pattern=["control_layers.{block}.attention.norm_k.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.attention_norm1.weight",
                from_pattern=["control_layers.{block}.attention_norm1.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.attention_norm2.weight",
                from_pattern=["control_layers.{block}.attention_norm2.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.ffn_norm1.weight",
                from_pattern=["control_layers.{block}.ffn_norm1.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.ffn_norm2.weight",
                from_pattern=["control_layers.{block}.ffn_norm2.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.feed_forward.w1.weight",
                from_pattern=["control_layers.{block}.feed_forward.w1.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.feed_forward.w2.weight",
                from_pattern=["control_layers.{block}.feed_forward.w2.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.feed_forward.w3.weight",
                from_pattern=["control_layers.{block}.feed_forward.w3.weight"],
                max_blocks=15,
            ),
            # Control projections (only some blocks have before_proj)
            WeightTarget(
                to_pattern="control_layers.{block}.before_proj.weight",
                from_pattern=["control_layers.{block}.before_proj.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.before_proj.bias",
                from_pattern=["control_layers.{block}.before_proj.bias"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.after_proj.weight",
                from_pattern=["control_layers.{block}.after_proj.weight"],
                max_blocks=15,
            ),
            WeightTarget(
                to_pattern="control_layers.{block}.after_proj.bias",
                from_pattern=["control_layers.{block}.after_proj.bias"],
                max_blocks=15,
            ),
            # Noise-refiner control blocks (Union: 2 blocks, 2.1 uses control_noise_refiner)
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.adaLN_modulation.0.weight",
                from_pattern=["control_noise_refiner.{block}.adaLN_modulation.0.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.adaLN_modulation.0.bias",
                from_pattern=["control_noise_refiner.{block}.adaLN_modulation.0.bias"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.attention.to_q.weight",
                from_pattern=["control_noise_refiner.{block}.attention.to_q.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.attention.to_k.weight",
                from_pattern=["control_noise_refiner.{block}.attention.to_k.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.attention.to_v.weight",
                from_pattern=["control_noise_refiner.{block}.attention.to_v.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.attention.to_out.0.weight",
                from_pattern=["control_noise_refiner.{block}.attention.to_out.0.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.attention.norm_q.weight",
                from_pattern=["control_noise_refiner.{block}.attention.norm_q.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.attention.norm_k.weight",
                from_pattern=["control_noise_refiner.{block}.attention.norm_k.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.attention_norm1.weight",
                from_pattern=["control_noise_refiner.{block}.attention_norm1.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.attention_norm2.weight",
                from_pattern=["control_noise_refiner.{block}.attention_norm2.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.ffn_norm1.weight",
                from_pattern=["control_noise_refiner.{block}.ffn_norm1.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.ffn_norm2.weight",
                from_pattern=["control_noise_refiner.{block}.ffn_norm2.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.feed_forward.w1.weight",
                from_pattern=["control_noise_refiner.{block}.feed_forward.w1.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.feed_forward.w2.weight",
                from_pattern=["control_noise_refiner.{block}.feed_forward.w2.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.feed_forward.w3.weight",
                from_pattern=["control_noise_refiner.{block}.feed_forward.w3.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.before_proj.weight",
                from_pattern=["control_noise_refiner.{block}.before_proj.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.before_proj.bias",
                from_pattern=["control_noise_refiner.{block}.before_proj.bias"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.after_proj.weight",
                from_pattern=["control_noise_refiner.{block}.after_proj.weight"],
                max_blocks=2,
            ),
            WeightTarget(
                to_pattern="control_noise_refiner.{block}.after_proj.bias",
                from_pattern=["control_noise_refiner.{block}.after_proj.bias"],
                max_blocks=2,
            ),
        ]
