from typing import List

from mflux.models.common.lora.mapping.lora_mapping import LoRAMapping, LoRATarget


class QwenLoRAMapping(LoRAMapping):

    @staticmethod
    def get_mapping() -> List[LoRATarget]:
        return [
            LoRATarget(
                model_path="transformer_blocks.{block}.attn.to_q",
                possible_up_patterns=[
                    "transformer_blocks.{block}.attn.to_q.lora_up.weight",
                    "transformer.transformer_blocks.{block}.attn.to_q.lora.up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.attn.to_q.lora_down.weight",
                    "transformer.transformer_blocks.{block}.attn.to_q.lora.down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.attn.to_q.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.attn.to_k",
                possible_up_patterns=[
                    "transformer_blocks.{block}.attn.to_k.lora_up.weight",
                    "transformer.transformer_blocks.{block}.attn.to_k.lora.up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.attn.to_k.lora_down.weight",
                    "transformer.transformer_blocks.{block}.attn.to_k.lora.down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.attn.to_k.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.attn.to_v",
                possible_up_patterns=[
                    "transformer_blocks.{block}.attn.to_v.lora_up.weight",
                    "transformer.transformer_blocks.{block}.attn.to_v.lora.up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.attn.to_v.lora_down.weight",
                    "transformer.transformer_blocks.{block}.attn.to_v.lora.down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.attn.to_v.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.attn.attn_to_out.0",
                possible_up_patterns=[
                    "transformer_blocks.{block}.attn.to_out.0.lora_up.weight",
                    "transformer.transformer_blocks.{block}.attn.to_out.0.lora.up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.attn.to_out.0.lora_down.weight",
                    "transformer.transformer_blocks.{block}.attn.to_out.0.lora.down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.attn.to_out.0.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.attn.add_q_proj",
                possible_up_patterns=[
                    "transformer_blocks.{block}.attn.add_q_proj.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.attn.add_q_proj.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.attn.add_q_proj.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.attn.add_k_proj",
                possible_up_patterns=[
                    "transformer_blocks.{block}.attn.add_k_proj.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.attn.add_k_proj.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.attn.add_k_proj.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.attn.add_v_proj",
                possible_up_patterns=[
                    "transformer_blocks.{block}.attn.add_v_proj.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.attn.add_v_proj.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.attn.add_v_proj.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.attn.to_add_out",
                possible_up_patterns=[
                    "transformer_blocks.{block}.attn.to_add_out.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.attn.to_add_out.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.attn.to_add_out.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.img_ff.mlp_in",
                possible_up_patterns=[
                    "transformer_blocks.{block}.img_mlp.net.0.proj.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.img_mlp.net.0.proj.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.img_mlp.net.0.proj.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.img_ff.mlp_out",
                possible_up_patterns=[
                    "transformer_blocks.{block}.img_mlp.net.2.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.img_mlp.net.2.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.img_mlp.net.2.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.txt_ff.mlp_in",
                possible_up_patterns=[
                    "transformer_blocks.{block}.txt_mlp.net.0.proj.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.txt_mlp.net.0.proj.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.txt_mlp.net.0.proj.alpha",
                ]
            ),
            LoRATarget(
                model_path="transformer_blocks.{block}.txt_ff.mlp_out",
                possible_up_patterns=[
                    "transformer_blocks.{block}.txt_mlp.net.2.lora_up.weight",
                ],
                possible_down_patterns=[
                    "transformer_blocks.{block}.txt_mlp.net.2.lora_down.weight",
                ],
                possible_alpha_patterns=[
                    "transformer_blocks.{block}.txt_mlp.net.2.alpha",
                ]
        ),
    ]

